"""Migrations on real MySQL: down, up again, and models that match (P-044, P-051)."""

import pytest
from alembic import command
from sqlalchemy import Engine, inspect, text

from tests.support import alembic_config

pytestmark = pytest.mark.integration

APP_TABLES = {"blobs", "documents", "projects", "users", "versions"}


def table_names(engine: Engine) -> set[str]:
    return set(inspect(engine).get_table_names())


def test_downgrade_then_upgrade_again(migrated: Engine) -> None:
    with migrated.begin() as connection:
        command.downgrade(alembic_config(connection), "base")
    assert table_names(migrated) == {"alembic_version"}

    with migrated.begin() as connection:
        command.upgrade(alembic_config(connection), "head")
    assert table_names(migrated) == APP_TABLES | {"alembic_version"}


def test_models_match_the_migrations(migrated: Engine) -> None:
    with migrated.connect() as connection:
        command.check(alembic_config(connection))  # raises AutoGenerateDiffsDetected


def test_tables_are_innodb_and_utf8mb4(migrated: Engine) -> None:
    query = text(
        "SELECT TABLE_NAME, ENGINE, TABLE_COLLATION FROM information_schema.TABLES "
        "WHERE TABLE_SCHEMA = DATABASE()"
    )
    with migrated.connect() as connection:
        rows = {name: (engine, collation) for name, engine, collation in connection.execute(query)}
    for table in APP_TABLES:
        assert rows[table] == ("InnoDB", "utf8mb4_0900_ai_ci")
